# Generated by Django 3.2.4 on 2021-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('H', 'Housing'), ('T', 'Transportation'), ('F', 'Food'), ('P', 'Pets'), ('E', 'Entertainment'), ('L', 'Loans'), ('S', 'Savings')], max_length=13),
        ),
    ]
